### ISSUE TITLE
Confusion of Alice and Bob?

### ISSUE THREAD

**Issue by starius** [supertestnet/hedgehog#1]
In this section https://github.com/supertestnet/hedgehog?tab=readme-ov-file#combining-them-hedgehog-channels

> Alice opens a channel with Bob by sending 10_000 sats into a standard multisig (Alice && Bob). Alice can send Bob 2_000 sats "off chain"

later:

> Alice’s new, off-chain balance: 2_500 sats (down ~2000 sats & a fee) Bob’s new, off-chain balance: 7_000 sats (up ~2000 sats) This is "State 2." (State 1 was just Alice: 10_000 sats, Bob: 0 sats)

10000 - 2000 = 8000 sats. IIUC, Alice's new balance should be 8k (or 7k, because of fees), not Bob's. Or the size of the offchain payment from Alice to Bob should be 7k, not 2k.

**Comment by supertestnet** [comment]
Oops, you are right! Sorry about that, I originally had them dual-fund the channel with 5k sats apiece, so when Alice sent Bob 2k sats, he went up to 7k and she went down to 3k (minus a fee). When I changed it to single-funded with Alice having 10k sats, I forgot to change some parts. I've fixed it now.
