### ISSUE TITLE
l2 delegated for different clients

### ISSUE THREAD

**Issue by ali2210** [supertestnet/hedgehog#4]
@supertestnet  Sir, I hope you will extend your work with more clients, this solution quite innovative .

- [ ] Rust
- [ ] Go
- [ ] Python 
- [ ] ios
- [ ] android

If you're interested in bitcoin devlopment projects or help us to make our dream come true with your service's that we are really appricate both parties win

**Comment by supertestnet** [comment]
Hi ali,

I probably won't make a client in Rust or Go as I don't know those languages. I am currently working on a javascript client which, if I finish it, I can probably release it as a progressive webapp for use on android and ios. A python app would be cool too. Please help by making clients in those other languages for me! :D
